# fly.toml app configuration file generated for jeheecheon-web on 2025-07-09T13:59:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jeheecheon-web'
primary_region = 'nrt'

[build]
  [build.args]
    VITE_BLOG_API_URL = "https://blog.jeheecheon.com:4001"
    VITE_BLOG_GRAPHQL_URL = "https://blog.jeheecheon.com:4001/graphql"

[processes]
  be-blog = "pnpm -F @apps/be-blog start:prod"
  fe-blog = "pnpm -F @apps/fe-blog start:prod"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[services]]
  processes = ["be-blog"]
  internal_port = 4001
  protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 4001

[[services]]
  processes = ["fe-blog"]
  internal_port = 4000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
